/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package funes.view;

import datos.PersonaDenunciada;
import funes.controller.ControladorBusquedaPersona;
import funes.model.Model;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Trei
 */
public class BusquedaPersona extends javax.swing.JFrame implements IBusquedaPersona {

    private ControladorBusquedaPersona Controlador;
    private ArrayList<String> listaResultados;
    private ArrayList<PersonaDenunciada> resultadosBuscarPersona;
    JLisResultados resultadosListaPanel = null;

    public BusquedaPersona(Model modelo) {
        initComponents();
        Controlador = new ControladorBusquedaPersona(modelo, this);
        vincularEventos();

    }

    public BusquedaPersona() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTituloBusqPersona = new javax.swing.JLabel();
        jButtonSalirBusquedaPersona = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombrePersona = new javax.swing.JTextField();
        jLabelCedula = new javax.swing.JLabel();
        jTextFieldCedulaPersona = new javax.swing.JTextField();
        jLabelApellido1 = new javax.swing.JLabel();
        jTextFieldApellido1Persona = new javax.swing.JTextField();
        jLabelapellido2 = new javax.swing.JLabel();
        jTextFieldApellido2Persona = new javax.swing.JTextField();
        ButtonBuscarPersona = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));

        jLabelTituloBusqPersona.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTituloBusqPersona.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloBusqPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/funes/view/imagenes/UserGrande.png"))); // NOI18N

        jButtonSalirBusquedaPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/funes/view/imagenes/Button-Close-icon_1.png"))); // NOI18N
        jButtonSalirBusquedaPersona.setBorder(null);
        jButtonSalirBusquedaPersona.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloBusqPersona)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalirBusquedaPersona)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSalirBusquedaPersona)
                    .addComponent(jLabelTituloBusqPersona)))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNombre.setText("Nombre");

        jLabelCedula.setText("Cédula");

        jLabelApellido1.setText("Primer Apellido");

        jLabelapellido2.setText("Segundo Apellido");

        ButtonBuscarPersona.setText("Buscar");
        ButtonBuscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBuscarPersonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelapellido2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldApellido2Persona))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelApellido1)
                        .addGap(23, 23, 23)
                        .addComponent(jTextFieldApellido1Persona, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombre)
                            .addComponent(jLabelCedula))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCedulaPersona, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(jTextFieldNombrePersona)))
                    .addComponent(ButtonBuscarPersona))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCedula)
                    .addComponent(jTextFieldCedulaPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellido1)
                    .addComponent(jTextFieldApellido1Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelapellido2)
                    .addComponent(jTextFieldApellido2Persona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonBuscarPersona)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonBuscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBuscarPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonBuscarPersonaActionPerformed

    public JButton getButtonBuscarPersona() {
        return ButtonBuscarPersona;
    }

    public JButton getjButtonSalirBusquedaPersona() {
        return jButtonSalirBusquedaPersona;
    }

    public JTextField getjTextFieldNombrePersona() {
        return jTextFieldNombrePersona;
    }

    public JTextField getjTextFieldApellido1Persona() {
        return jTextFieldApellido1Persona;
    }

    public JTextField getjTextFieldApellido2Persona() {
        return jTextFieldApellido2Persona;
    }

    public JTextField getjTextFieldCedulaPersona() {
        return jTextFieldCedulaPersona;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusquedaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusquedaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusquedaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusquedaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusquedaPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBuscarPersona;
    private javax.swing.JButton jButtonSalirBusquedaPersona;
    private javax.swing.JLabel jLabelApellido1;
    private javax.swing.JLabel jLabelCedula;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTituloBusqPersona;
    private javax.swing.JLabel jLabelapellido2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldApellido1Persona;
    private javax.swing.JTextField jTextFieldApellido2Persona;
    private javax.swing.JTextField jTextFieldCedulaPersona;
    private javax.swing.JTextField jTextFieldNombrePersona;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarMensajeError(String mensaje, String titulo) {

        JOptionPane.showMessageDialog(null,
                mensaje,
                titulo,
                JOptionPane.ERROR_MESSAGE);

    }

    @Override
    public void vincularEventos() {
        ButtonBuscarPersona.addActionListener(Controlador);
        jButtonSalirBusquedaPersona.addActionListener(Controlador);
    }

    @Override
    public void mostrarVentana() {
        setVisible(true);
    }

    @Override
    public void ocultarVentana() {
        setVisible(false);
    }

    public void mostrarResultados(ArrayList<PersonaDenunciada> solicitudBuscarPersona) {

        resultadosBuscarPersona = solicitudBuscarPersona;
        listaResultados = new ArrayList<>();
        for (int entidad = 0; entidad < solicitudBuscarPersona.size(); entidad++) {
            //System.out.println(solicitudBuscarPersona.get(entidad).getSegundoApellido());
            String datos = solicitudBuscarPersona.get(entidad).getDatosGenerales();
            listaResultados.add(datos);
            System.out.println(datos);
        }

        String[] listaDatosAMostrar = listaResultados.toArray(new String[listaResultados.size()]);
        if (resultadosListaPanel != null) {
            resultadosListaPanel.dispose();
        }
        resultadosListaPanel = new JLisResultados(listaDatosAMostrar);
        resultadosListaPanel.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    @Override
    public void setNombre() {
        jTextFieldNombrePersona.setText("");
    }

    @Override
    public void setCedula() {
        jTextFieldCedulaPersona.setText("");
    }

    @Override
    public void setPrimerApellido() {
        jTextFieldApellido1Persona.setText("");
    }

    @Override
    public void setSegundoApellido() {
        jTextFieldApellido2Persona.setText("");
    }

    class JLisResultados extends JFrame {

        JList list;

        Container contentpane;

        public JLisResultados(String[] listColorNames) {
            super("Resultados");
            contentpane = getContentPane();
            contentpane.setLayout(new FlowLayout());
            contentpane.setBackground(Color.orange);
            
            list = new JList(listColorNames);
            //list.setSelectedIndex(0);
            list.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            contentpane.add(new JScrollPane(list));
            list.addListSelectionListener(new ListSelectionListener() {

                public void valueChanged(ListSelectionEvent e) {
                    int selectedIndex = list.getSelectedIndex();
                    PersonaDenunciada persona = resultadosBuscarPersona.get(selectedIndex);
                    String nombre = persona.getNombre();
                    String cedula = persona.getCedula();
                    String institucionLaboral = persona.getInstitucionLaboral();
                    String cargo = persona.getCargo();
                    Controlador.mostrarVentanaPersonaDenunciada(nombre, cedula, institucionLaboral, cargo);
                }
            });
             setSize(360,208);
            setVisible(true);
        }
    }
}
