/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package funes.view;

import datos.EntidadDenunciada;
import funes.model.Model;
import funes.controller.ControladorBuscarEntidad;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Trei
 */
public class BusquedaEntidad extends javax.swing.JFrame implements IBusquedaEntidad {

    private ArrayList<String> listaResultados;
    private ArrayList<EntidadDenunciada> resultadosBuscarEntidad;
    JLisResultados resultadosListaPanel = null;

    /**
     * Creates new form NewJFrameBusquedaEntidad
     */
    private ControladorBuscarEntidad Controlador;

    public BusquedaEntidad(Model modelo) {
        initComponents();
        Controlador = new ControladorBuscarEntidad(modelo, this);
        vincularEventos();

    }

    public BusquedaEntidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTituloBusqEntidad = new javax.swing.JLabel();
        jButtonSalirBusquedaEntidad = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombreEntidad = new javax.swing.JTextField();
        jLabelCedJ = new javax.swing.JLabel();
        jTextFieldCedJuridica = new javax.swing.JTextField();
        jButtonBuscarEntidad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));

        jLabelTituloBusqEntidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelTituloBusqEntidad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloBusqEntidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/funes/view/imagenes/Briefcase-iconGrande.png"))); // NOI18N

        jButtonSalirBusquedaEntidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/funes/view/imagenes/Button-Close-icon_1.png"))); // NOI18N
        jButtonSalirBusquedaEntidad.setBorder(null);
        jButtonSalirBusquedaEntidad.setContentAreaFilled(false);
        jButtonSalirBusquedaEntidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirBusquedaEntidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloBusqEntidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalirBusquedaEntidad)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSalirBusquedaEntidad)
                    .addComponent(jLabelTituloBusqEntidad))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNombre.setText("Nombre");

        jLabelCedJ.setText("Cédula Jurídica");

        jButtonBuscarEntidad.setText("Buscar");
        jButtonBuscarEntidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarEntidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonBuscarEntidad))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabelCedJ, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNombreEntidad, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(jTextFieldCedJuridica))))
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombreEntidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCedJ)
                    .addComponent(jTextFieldCedJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBuscarEntidad)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarEntidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarEntidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarEntidadActionPerformed

    private void jButtonSalirBusquedaEntidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirBusquedaEntidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirBusquedaEntidadActionPerformed

    public JButton getjButtonBuscarEntidad() {
        return jButtonBuscarEntidad;
    }

    public JTextField getjTextFieldCedJuridica() {
        return jTextFieldCedJuridica;
    }

    public JTextField getjTextFieldNombreEntidad() {
        return jTextFieldNombreEntidad;
    }

    public JButton getjButtonSalirBusquedaEntidad() {
        return jButtonSalirBusquedaEntidad;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusquedaEntidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusquedaEntidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusquedaEntidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusquedaEntidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusquedaEntidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarEntidad;
    private javax.swing.JButton jButtonSalirBusquedaEntidad;
    private javax.swing.JLabel jLabelCedJ;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTituloBusqEntidad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldCedJuridica;
    private javax.swing.JTextField jTextFieldNombreEntidad;
    // End of variables declaration//GEN-END:variables

    public void mostrarMensajeError(String mensaje, String titulo) {
        JOptionPane.showMessageDialog(null,
                mensaje,
                titulo,
                JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public void vincularEventos() {

        jButtonBuscarEntidad.addActionListener(Controlador);
        jButtonSalirBusquedaEntidad.addActionListener(Controlador);

    }

    @Override
    public void mostrarVentana() {
        setVisible(true);
    }

    @Override
    public void ocultarVentana() {
        setVisible(false);
    }

    public void mostrarResultados(ArrayList<EntidadDenunciada> solicitudEntidad) {

        resultadosBuscarEntidad = solicitudEntidad;
        listaResultados = new ArrayList<>();
        for (int entidad = 0; entidad < solicitudEntidad.size(); entidad++) {
            String datos = solicitudEntidad.get(entidad).getDatosGenerales();
            listaResultados.add(datos);
            System.out.println(datos);
        }

        String[] listaDatosAMostrar = listaResultados.toArray(new String[listaResultados.size()]);
        if (resultadosListaPanel != null) {
            resultadosListaPanel.dispose();
        }
        resultadosListaPanel = new JLisResultados(listaDatosAMostrar);
        resultadosListaPanel.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    @Override
    public void setNombreEntidad() {
        jTextFieldNombreEntidad.setText("");
    }

    @Override
    public void setCedulaJuridica() {
       jTextFieldCedJuridica.setText("");
    }

    class JLisResultados extends JFrame {

        JList list;

        Container contentpane;

        public JLisResultados(String[] listColorNames) {
            super("Resultados");
            contentpane = getContentPane();
            contentpane.setLayout(new FlowLayout());
            contentpane.setBackground(Color.orange);
            
            list = new JList(listColorNames);
            //list.setSelectedIndex(0);
            list.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            contentpane.add(new JScrollPane(list));

            list.addListSelectionListener(new ListSelectionListener() {

                public void valueChanged(ListSelectionEvent e) {
                    int selectedIndex = list.getSelectedIndex();
                    EntidadDenunciada entidad = resultadosBuscarEntidad.get(selectedIndex);
                    String nombre = entidad.getNombre();
                    String cedula = entidad.getCedulaJuridica();
                    String provincia = entidad.getProvincia();

                    System.out.println("CAMBIA INDICE");
                    Controlador.mostrarVentanaEntidadDenunciada(nombre, cedula, provincia);
                }
            });
            setSize(360,220);
            setVisible(true);
        }
    }

}
