/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package funes.view;

import javax.swing.JButton;
import javax.swing.JRadioButton;
import funes.controller.ControladorPerfilUsuario;
import funes.model.Model;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author USUARIO
 */
public class PerfilUsuario extends javax.swing.JFrame implements IPerfilUsuario {

    /**
     * Creates new form PerfilUsuario
     */
    private ControladorPerfilUsuario Controlador;

    public PerfilUsuario(Model modelo) {
        initComponents();
        buttonGroupPrivado.add(jRadioButtonPrivadoSi);
        buttonGroupPrivado.add(jRadioButtonPrivadoNo);
        Controlador = new ControladorPerfilUsuario(modelo, this);
        vincularEventos();

    }

    public PerfilUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPrivado = new javax.swing.ButtonGroup();
        jPanelPerfilUsuario = new javax.swing.JPanel();
        jPanelInformacionPersonal = new javax.swing.JPanel();
        jLabelNombreCompletoUsuario = new javax.swing.JLabel();
        jLabelCedulaUsuario = new javax.swing.JLabel();
        jLabelGeneroUsuario = new javax.swing.JLabel();
        jLabelFechaDeNacimientoUsuario = new javax.swing.JLabel();
        jLabelEdadUsuario = new javax.swing.JLabel();
        jLabelLugarDeTrabajoUsuario = new javax.swing.JLabel();
        jLabelCargoUsuario = new javax.swing.JLabel();
        jTextFieldNombreCompletoUsuario = new javax.swing.JTextField();
        jTextFieldCedulaUsuario = new javax.swing.JTextField();
        jRadioButtonGeneroFemeninoUsuario = new javax.swing.JRadioButton();
        jRadioButtonGeneroMasculinoUsuario = new javax.swing.JRadioButton();
        jComboBoxDiaNacimientoUsuario = new javax.swing.JComboBox();
        jComboBoxMesNacimientoUsuario = new javax.swing.JComboBox();
        jTextFieldAnnoNacimientoUsuario = new javax.swing.JTextField();
        jTextFieldEdadUsuario = new javax.swing.JTextField();
        jTextFieldLugarDeTrabajoUsuario = new javax.swing.JTextField();
        jTextFieldCargoUsuario = new javax.swing.JTextField();
        jLabelInformacionPersonal = new javax.swing.JLabel();
        jLabelPrivadoUsuario = new javax.swing.JLabel();
        jRadioButtonPrivadoSi = new javax.swing.JRadioButton();
        jRadioButtonPrivadoNo = new javax.swing.JRadioButton();
        jButtonEditarInformacionPersonalUsuario = new javax.swing.JButton();
        jButtonGuardarInformacionPersonal = new javax.swing.JButton();
        jPanelNickname = new javax.swing.JPanel();
        jLabelNickname = new javax.swing.JLabel();
        jLabelDenunciarOpciones = new javax.swing.JLabel();
        jButtonDenunciarPersona = new javax.swing.JButton();
        jButtonDenunciarEntidad = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jPanelCuenta = new javax.swing.JPanel();
        jLabelCuenta = new javax.swing.JLabel();
        jLabelNicknameUsuario = new javax.swing.JLabel();
        jLabelContrasennaUsuario = new javax.swing.JLabel();
        jTextFieldNicknameUsuario = new javax.swing.JTextField();
        jTextFieldContrasennaUsuario = new javax.swing.JTextField();
        jButtonEditarCuenta = new javax.swing.JButton();
        jButtonGuardarInformacionCuenta = new javax.swing.JButton();
        jButtonCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelInformacionPersonal.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInformacionPersonal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelNombreCompletoUsuario.setText("Nombre Completo: ");

        jLabelCedulaUsuario.setText("Cédula: ");

        jLabelGeneroUsuario.setText("Género: ");

        jLabelFechaDeNacimientoUsuario.setText("Fecha de nacimiento:");

        jLabelEdadUsuario.setText("Edad: ");

        jLabelLugarDeTrabajoUsuario.setText("Lugar de trabajo: ");

        jLabelCargoUsuario.setText("Cargo: ");

        jTextFieldNombreCompletoUsuario.setEnabled(false);
        jTextFieldNombreCompletoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreCompletoUsuarioActionPerformed(evt);
            }
        });

        jTextFieldCedulaUsuario.setEnabled(false);
        jTextFieldCedulaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCedulaUsuarioActionPerformed(evt);
            }
        });

        jRadioButtonGeneroFemeninoUsuario.setText("F");
        jRadioButtonGeneroFemeninoUsuario.setEnabled(false);

        jRadioButtonGeneroMasculinoUsuario.setText("M");
        jRadioButtonGeneroMasculinoUsuario.setEnabled(false);

        jComboBoxDiaNacimientoUsuario.setEditable(true);
        jComboBoxDiaNacimientoUsuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBoxDiaNacimientoUsuario.setEnabled(false);

        jComboBoxMesNacimientoUsuario.setEditable(true);
        jComboBoxMesNacimientoUsuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jComboBoxMesNacimientoUsuario.setEnabled(false);
        jComboBoxMesNacimientoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMesNacimientoUsuarioActionPerformed(evt);
            }
        });

        jTextFieldAnnoNacimientoUsuario.setEnabled(false);
        jTextFieldAnnoNacimientoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAnnoNacimientoUsuarioActionPerformed(evt);
            }
        });

        jTextFieldEdadUsuario.setEnabled(false);

        jTextFieldLugarDeTrabajoUsuario.setEnabled(false);

        jTextFieldCargoUsuario.setEnabled(false);

        jLabelInformacionPersonal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelInformacionPersonal.setText("Información Personal");

        jLabelPrivadoUsuario.setText("Privado:");

        jRadioButtonPrivadoSi.setText("Sí");
        jRadioButtonPrivadoSi.setEnabled(false);

        jRadioButtonPrivadoNo.setText("No");
        jRadioButtonPrivadoNo.setEnabled(false);

        jButtonEditarInformacionPersonalUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/funes/view/imagenes/editar.png"))); // NOI18N
        jButtonEditarInformacionPersonalUsuario.setBorder(null);
        jButtonEditarInformacionPersonalUsuario.setContentAreaFilled(false);

        jButtonGuardarInformacionPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/funes/view/imagenes/save.png"))); // NOI18N
        jButtonGuardarInformacionPersonal.setBorder(null);
        jButtonGuardarInformacionPersonal.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanelInformacionPersonalLayout = new javax.swing.GroupLayout(jPanelInformacionPersonal);
        jPanelInformacionPersonal.setLayout(jPanelInformacionPersonalLayout);
        jPanelInformacionPersonalLayout.setHorizontalGroup(
            jPanelInformacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInformacionPersonalLayout.createSequentialGroup()
                .addGroup(jPanelInformacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelInformacionPersonalLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEditarInformacionPersonalUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelInformacionPersonal))
                    .addGroup(jPanelInformacionPersonalLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanelInformacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombreCompletoUsuario)
                            .addComponent(jLabelCedulaUsuario)
                            .addComponent(jLabelGeneroUsuario)
                            .addComponent(jLabelFechaDeNacimientoUsuario)
                            .addComponent(jLabelEdadUsuario)
                            .addComponent(jLabelLugarDeTrabajoUsuario)
                            .addComponent(jLabelPrivadoUsuario)
                            .addComponent(jLabelCargoUsuario))
                        .addGap(27, 27, 27)
                        .addGroup(jPanelInformacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNombreCompletoUsuario)
                            .addComponent(jTextFieldCedulaUsuario)
                            .addComponent(jTextFieldLugarDeTrabajoUsuario)
                            .addComponent(jTextFieldCargoUsuario)
                            .addGroup(jPanelInformacionPersonalLayout.createSequentialGroup()
                                .addGroup(jPanelInformacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldEdadUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelInformacionPersonalLayout.createSequentialGroup()
                                        .addGroup(jPanelInformacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jComboBoxDiaNacimientoUsuario, 0, 1, Short.MAX_VALUE)
                                            .addComponent(jRadioButtonGeneroFemeninoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanelInformacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButtonGeneroMasculinoUsuario)
                                            .addGroup(jPanelInformacionPersonalLayout.createSequentialGroup()
                                                .addComponent(jComboBoxMesNacimientoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextFieldAnnoNacimientoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE))
                            .addGroup(jPanelInformacionPersonalLayout.createSequentialGroup()
                                .addComponent(jRadioButtonPrivadoSi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonPrivadoNo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonGuardarInformacionPersonal)))))
                .addGap(30, 30, 30))
        );
        jPanelInformacionPersonalLayout.setVerticalGroup(
            jPanelInformacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformacionPersonalLayout.createSequentialGroup()
                .addGroup(jPanelInformacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInformacionPersonalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelInformacionPersonal))
                    .addComponent(jButtonEditarInformacionPersonalUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInformacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreCompletoUsuario)
                    .addComponent(jTextFieldNombreCompletoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInformacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCedulaUsuario)
                    .addComponent(jTextFieldCedulaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelInformacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInformacionPersonalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelInformacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelGeneroUsuario)
                            .addComponent(jRadioButtonGeneroFemeninoUsuario)
                            .addComponent(jRadioButtonGeneroMasculinoUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelInformacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFechaDeNacimientoUsuario)
                            .addComponent(jComboBoxDiaNacimientoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxMesNacimientoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAnnoNacimientoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelInformacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEdadUsuario)
                            .addComponent(jTextFieldEdadUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelInformacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLugarDeTrabajoUsuario)
                            .addComponent(jTextFieldLugarDeTrabajoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelInformacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCargoUsuario)
                            .addComponent(jTextFieldCargoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelInformacionPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPrivadoUsuario)
                            .addComponent(jRadioButtonPrivadoSi)
                            .addComponent(jRadioButtonPrivadoNo))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInformacionPersonalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonGuardarInformacionPersonal)
                        .addContainerGap())))
        );

        jPanelNickname.setBackground(new java.awt.Color(153, 0, 153));
        jPanelNickname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelNickname.setForeground(new java.awt.Color(255, 255, 255));

        jLabelNickname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelNickname.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNickname.setText("NickName");

        jLabelDenunciarOpciones.setFont(new java.awt.Font("Utsaah", 0, 14)); // NOI18N
        jLabelDenunciarOpciones.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDenunciarOpciones.setText("Denúncie");

        jButtonDenunciarPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/funes/view/imagenes/user.png"))); // NOI18N
        jButtonDenunciarPersona.setBorder(null);
        jButtonDenunciarPersona.setBorderPainted(false);
        jButtonDenunciarPersona.setContentAreaFilled(false);
        jButtonDenunciarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDenunciarPersonaActionPerformed(evt);
            }
        });

        jButtonDenunciarEntidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/funes/view/imagenes/Briefcase-icon.png"))); // NOI18N
        jButtonDenunciarEntidad.setBorder(null);
        jButtonDenunciarEntidad.setContentAreaFilled(false);
        jButtonDenunciarEntidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDenunciarEntidadActionPerformed(evt);
            }
        });

        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/funes/view/imagenes/find-icon.png"))); // NOI18N
        jButtonBuscar.setBorder(null);
        jButtonBuscar.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanelNicknameLayout = new javax.swing.GroupLayout(jPanelNickname);
        jPanelNickname.setLayout(jPanelNicknameLayout);
        jPanelNicknameLayout.setHorizontalGroup(
            jPanelNicknameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNicknameLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabelNickname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelDenunciarOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDenunciarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDenunciarEntidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelNicknameLayout.setVerticalGroup(
            jPanelNicknameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNicknameLayout.createSequentialGroup()
                .addGroup(jPanelNicknameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonDenunciarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDenunciarEntidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNicknameLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelNicknameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNicknameLayout.createSequentialGroup()
                        .addComponent(jLabelDenunciarOpciones)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelNicknameLayout.createSequentialGroup()
                        .addComponent(jLabelNickname)
                        .addContainerGap())))
        );

        jPanelCuenta.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCuenta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelCuenta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCuenta.setText("Cuenta");

        jLabelNicknameUsuario.setText("NickName:");

        jLabelContrasennaUsuario.setText("Contraseña:");

        jTextFieldNicknameUsuario.setEnabled(false);

        jTextFieldContrasennaUsuario.setEnabled(false);

        jButtonEditarCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/funes/view/imagenes/editar.png"))); // NOI18N
        jButtonEditarCuenta.setBorder(null);
        jButtonEditarCuenta.setContentAreaFilled(false);

        jButtonGuardarInformacionCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/funes/view/imagenes/save.png"))); // NOI18N
        jButtonGuardarInformacionCuenta.setBorder(null);
        jButtonGuardarInformacionCuenta.setContentAreaFilled(false);

        jButtonCerrarSesion.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jButtonCerrarSesion.setText("Cerrar Sesión");
        jButtonCerrarSesion.setBorder(null);
        jButtonCerrarSesion.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanelCuentaLayout = new javax.swing.GroupLayout(jPanelCuenta);
        jPanelCuenta.setLayout(jPanelCuentaLayout);
        jPanelCuentaLayout.setHorizontalGroup(
            jPanelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCuentaLayout.createSequentialGroup()
                .addGroup(jPanelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCuentaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonGuardarInformacionCuenta))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCuentaLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCuentaLayout.createSequentialGroup()
                                .addGroup(jPanelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNicknameUsuario)
                                    .addComponent(jLabelContrasennaUsuario))
                                .addGap(70, 70, 70)
                                .addGroup(jPanelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNicknameUsuario)
                                    .addComponent(jTextFieldContrasennaUsuario)))
                            .addGroup(jPanelCuentaLayout.createSequentialGroup()
                                .addComponent(jButtonCerrarSesion)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanelCuentaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEditarCuenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCuenta)))
                .addGap(30, 30, 30))
        );
        jPanelCuentaLayout.setVerticalGroup(
            jPanelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCuentaLayout.createSequentialGroup()
                .addGroup(jPanelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCuentaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelCuenta))
                    .addComponent(jButtonEditarCuenta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNicknameUsuario)
                    .addComponent(jTextFieldNicknameUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContrasennaUsuario)
                    .addComponent(jTextFieldContrasennaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGuardarInformacionCuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCerrarSesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelPerfilUsuarioLayout = new javax.swing.GroupLayout(jPanelPerfilUsuario);
        jPanelPerfilUsuario.setLayout(jPanelPerfilUsuarioLayout);
        jPanelPerfilUsuarioLayout.setHorizontalGroup(
            jPanelPerfilUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNickname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelPerfilUsuarioLayout.createSequentialGroup()
                .addComponent(jPanelInformacionPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanelCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelPerfilUsuarioLayout.setVerticalGroup(
            jPanelPerfilUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPerfilUsuarioLayout.createSequentialGroup()
                .addComponent(jPanelNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanelInformacionPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPerfilUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPerfilUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCedulaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCedulaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCedulaUsuarioActionPerformed

    private void jTextFieldNombreCompletoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreCompletoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreCompletoUsuarioActionPerformed

    private void jTextFieldAnnoNacimientoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAnnoNacimientoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAnnoNacimientoUsuarioActionPerformed

    private void jButtonDenunciarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDenunciarPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDenunciarPersonaActionPerformed

    private void jButtonDenunciarEntidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDenunciarEntidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDenunciarEntidadActionPerformed

    private void jComboBoxMesNacimientoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMesNacimientoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMesNacimientoUsuarioActionPerformed

    public JButton getjButtonBuscar() {
        return jButtonBuscar;
    }

    public JButton getjButtonDenunciarPersona() {
        return jButtonDenunciarPersona;
    }

    public JButton getjButtonDenunciarEntidad() {
        return jButtonDenunciarEntidad;
    }

    public JButton getjButtonEditarInformacionPersonalUsuario() {
        return jButtonEditarInformacionPersonalUsuario;
    }

    public JButton getjButtonEditarCuenta() {
        return jButtonEditarCuenta;
    }

    public JRadioButton getjRadioButtonPrivadoSi() {
        return jRadioButtonPrivadoSi;
    }

    public JRadioButton getjRadioButtonPrivadoNo() {
        return jRadioButtonPrivadoNo;
    }

    public JButton getjButtonGuardarInformacionCuenta() {
        return jButtonGuardarInformacionCuenta;
    }

    public JButton getjButtonGuardarInformacionPersonal() {
        return jButtonGuardarInformacionPersonal;
    }

    public JButton getjButtonCerrarSesion() {
        return jButtonCerrarSesion;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PerfilUsuario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupPrivado;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonDenunciarEntidad;
    private javax.swing.JButton jButtonDenunciarPersona;
    private javax.swing.JButton jButtonEditarCuenta;
    private javax.swing.JButton jButtonEditarInformacionPersonalUsuario;
    private javax.swing.JButton jButtonGuardarInformacionCuenta;
    private javax.swing.JButton jButtonGuardarInformacionPersonal;
    private javax.swing.JComboBox jComboBoxDiaNacimientoUsuario;
    private javax.swing.JComboBox jComboBoxMesNacimientoUsuario;
    private javax.swing.JLabel jLabelCargoUsuario;
    private javax.swing.JLabel jLabelCedulaUsuario;
    private javax.swing.JLabel jLabelContrasennaUsuario;
    private javax.swing.JLabel jLabelCuenta;
    private javax.swing.JLabel jLabelDenunciarOpciones;
    private javax.swing.JLabel jLabelEdadUsuario;
    private javax.swing.JLabel jLabelFechaDeNacimientoUsuario;
    private javax.swing.JLabel jLabelGeneroUsuario;
    private javax.swing.JLabel jLabelInformacionPersonal;
    private javax.swing.JLabel jLabelLugarDeTrabajoUsuario;
    private javax.swing.JLabel jLabelNickname;
    private javax.swing.JLabel jLabelNicknameUsuario;
    private javax.swing.JLabel jLabelNombreCompletoUsuario;
    private javax.swing.JLabel jLabelPrivadoUsuario;
    private javax.swing.JPanel jPanelCuenta;
    private javax.swing.JPanel jPanelInformacionPersonal;
    private javax.swing.JPanel jPanelNickname;
    private javax.swing.JPanel jPanelPerfilUsuario;
    private javax.swing.JRadioButton jRadioButtonGeneroFemeninoUsuario;
    private javax.swing.JRadioButton jRadioButtonGeneroMasculinoUsuario;
    private javax.swing.JRadioButton jRadioButtonPrivadoNo;
    private javax.swing.JRadioButton jRadioButtonPrivadoSi;
    private javax.swing.JTextField jTextFieldAnnoNacimientoUsuario;
    private javax.swing.JTextField jTextFieldCargoUsuario;
    private javax.swing.JTextField jTextFieldCedulaUsuario;
    private javax.swing.JTextField jTextFieldContrasennaUsuario;
    private javax.swing.JTextField jTextFieldEdadUsuario;
    private javax.swing.JTextField jTextFieldLugarDeTrabajoUsuario;
    private javax.swing.JTextField jTextFieldNicknameUsuario;
    private javax.swing.JTextField jTextFieldNombreCompletoUsuario;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarMensajeError(String mensaje, String titulo) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void vincularEventos() {
        jButtonBuscar.addActionListener(Controlador);
        jButtonDenunciarEntidad.addActionListener(Controlador);
        jButtonDenunciarPersona.addActionListener(Controlador);
        jButtonEditarCuenta.addActionListener(Controlador);
        jButtonEditarInformacionPersonalUsuario.addActionListener(Controlador);
        jButtonGuardarInformacionCuenta.addActionListener(Controlador);
        jButtonGuardarInformacionPersonal.addActionListener(Controlador);
        jButtonCerrarSesion.addActionListener(Controlador);
    }

    @Override
    public void mostrarVentana() {
        setVisible(true);
    }

    @Override
    public void ocultarVentana() {
        setVisible(false);
    }

    @Override
    public void setNicknameLabel(String nickname) {
        jLabelNickname.setText(nickname);
    }

    @Override
    public void setNickname(String nickname) {
        jTextFieldNicknameUsuario.setText(nickname);
    }

    @Override
    public void setContrasenna(String contrasenna) {
        jTextFieldContrasennaUsuario.setText(contrasenna);
    }

    @Override
    public void setNombreCompleto(String nombreCompleto) {
        jTextFieldNombreCompletoUsuario.setText(nombreCompleto);
    }

    @Override
    public void setGenero(String genero) {
        if (genero == Constantes.FEMENINO) {
            jRadioButtonGeneroFemeninoUsuario.setSelected(true);
            jRadioButtonGeneroMasculinoUsuario.setSelected(false);
        } else if (genero == Constantes.MASCULINO) {
            jRadioButtonGeneroFemeninoUsuario.setSelected(false);
            jRadioButtonGeneroMasculinoUsuario.setSelected(true);
        }
    }

    @Override
    public void setAnnoNacimiento(String anno) {
        jTextFieldAnnoNacimientoUsuario.setText(anno);
    }

    @Override
    public void setEdad(String edad) {
        jTextFieldEdadUsuario.setText(edad);
    }

    @Override
    public void setLugarDeTrabajo(String lugarDeTrabajo) {
        jTextFieldLugarDeTrabajoUsuario.setText(lugarDeTrabajo);
    }

    @Override
    public void setCargo(String cargo) {
        jTextFieldCargoUsuario.setText(cargo);
    }

    @Override
    public void setPrivado(String privado) {
        if (privado == "Privado") {
            jRadioButtonPrivadoSi.setSelected(true);
            jRadioButtonPrivadoNo.setSelected(false);
        } else if (privado == "Publico") {
            jRadioButtonPrivadoNo.setSelected(true);
            jRadioButtonPrivadoSi.setSelected(false);
        }
    }

    @Override
    public void setCedula(String cedula) {
        jTextFieldCedulaUsuario.setText(cedula);
    }

    @Override
    public void setDiaNacimiento(String dia) {
        jComboBoxDiaNacimientoUsuario.setSelectedItem(dia);
    }

    @Override
    public void setMesNacimiento(String mes) {
        jComboBoxMesNacimientoUsuario.setSelectedItem(mes);
    }

    @Override
    public void habilitarContrasenna() {
        //jTextFieldContrasennaUsuario.setEditable(true);
        jTextFieldContrasennaUsuario.setEnabled(true);
    }

    @Override
    public void deshabilitarContrasenna() {
        //jTextFieldContrasennaUsuario.setEditable(false);
        jTextFieldContrasennaUsuario.setEnabled(false);
    }

    @Override
    public void habilitarFechaDeNacimiento() {
        jComboBoxDiaNacimientoUsuario.setEnabled(true);
        jComboBoxMesNacimientoUsuario.setEnabled(true);
        jTextFieldAnnoNacimientoUsuario.setEnabled(true);
    }

    @Override
    public void deshabilitarFechaDeNacimiento() {
        jComboBoxDiaNacimientoUsuario.setEnabled(false);
        jComboBoxMesNacimientoUsuario.setEnabled(false);
        jTextFieldAnnoNacimientoUsuario.setEnabled(false);
    }

    @Override
    public void habilitarLugarDeTrabajo() {
        jTextFieldLugarDeTrabajoUsuario.setEnabled(true);
    }

    @Override
    public void deshabilitarLugarDeTrabajo() {
        jTextFieldLugarDeTrabajoUsuario.setEnabled(false);
    }

    @Override
    public void habilitarCargo() {
        jTextFieldCargoUsuario.setEnabled(true);
    }

    @Override
    public void deshabilitarCargo() {
        jTextFieldCargoUsuario.setEnabled(false);
    }

    @Override
    public void habilitarPrivado() {
        jRadioButtonPrivadoNo.setEnabled(true);
        jRadioButtonPrivadoSi.setEnabled(true);
    }

    @Override
    public void deshabilitarPrivado() {
        jRadioButtonPrivadoNo.setEnabled(false);
        jRadioButtonPrivadoSi.setEnabled(false);
    }

    @Override
    public String getNickname() {
        return jTextFieldNicknameUsuario.getText();
    }

    @Override
    public String getContrasenna() {
        return jTextFieldContrasennaUsuario.getText();
    }

    @Override
    public String getDiaDeNacimiento() {
        return jComboBoxDiaNacimientoUsuario.getSelectedItem().toString();
    }

    @Override
    public String getMesNacimiento() {
        return jComboBoxMesNacimientoUsuario.getSelectedItem().toString();
    }

    @Override
    public String getAnnoNacimiento() {
        return jTextFieldAnnoNacimientoUsuario.getText();
    }

    @Override
    public String getLugarDeTrabajo() {
        return jTextFieldLugarDeTrabajoUsuario.getText();
    }

    @Override
    public String getCargo() {
        return jTextFieldCargoUsuario.getText();
    }

    @Override
    public String getPrivado() {
        if (jRadioButtonPrivadoSi.isSelected()) {
            return "Privado";
        } else {
            return "Publico";
        }
    }

    @Override
    public String getCedula() {
        return jTextFieldCedulaUsuario.getText();
    }
}
