/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package funes.view;

import funes.controller.ControllerRegistroNuevoUsuario;
import funes.model.Model;
import java.util.Arrays;
import javax.swing.ButtonModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author USUARIO
 */
public class RegistroNuevoUsuario extends javax.swing.JFrame implements IRegistroNuevoUsuario {

    private String cedulaActual;
    private boolean busquedaExitosa;

    //Lleva la referencia al controlador de la ventana
    private ControllerRegistroNuevoUsuario Controlador;

    /**
     * Creates new form RegistroNuevoUsuario
     */
    public RegistroNuevoUsuario(Model Modelo) {
        initComponents();
        buttonGroupPrivado.add(jRadioButtonDatosPrivadosUsuario);
        buttonGroupPrivado.add(jRadioButtonDatosPublicosUsuario);
        buttonGroupGenero.add(jRadioButtonGeneroFemenino);
        buttonGroupGenero.add(jRadioButtonGeneroMasculino);
        //Se conecta el modelo con la ventana y el controlador
        Controlador = new ControllerRegistroNuevoUsuario(Modelo, this);
        vincularEventos();

        //
        //Cambio de contructor
        ///DENIS
    }

    //Para pruebas sin vinculacion entre el modelo, controlador y ventana
    public RegistroNuevoUsuario() {
        initComponents();
    }

    @Override
    public void vincularEventos() {
        jButtonBuscarPersona.addActionListener(Controlador);
        jButtonRegistrarse.addActionListener(Controlador);
        jButtonTerminosyCondiciones.addActionListener(Controlador);
        jButtonSalirDeRegistro.addActionListener(Controlador);
    }

    public JButton getjButtonSalirDeRegistro() {
        return jButtonSalirDeRegistro;
    }

    
    public JButton getjButtonBuscarPersona() {
        return jButtonBuscarPersona;
    }

    public JButton getjButtonRegistrarse() {
        return jButtonRegistrarse;
    }

    public JComboBox getjComboBoxDiaNacimiento() {
        return jComboBoxDiaNacimiento;
    }

    public JComboBox getjComboBoxMesNacimiento() {
        return jComboBoxMesNacimiento;
    }

    public JTextField getjTextFieldAnnoNacimiento() {
        return jTextFieldAnnoNacimiento;
    }

    public JComboBox getjComboBoxProvincia() {
        return jComboBoxProvincia;
    }

    public JTextField getjTextFieldCedula() {
        return jTextFieldCedula;
    }

    public void setCedulaActual(String cedulaActual) {
        this.cedulaActual = cedulaActual;
    }

    public String getCedulaActual() {
        return cedulaActual;
    }

    public void setjTextFieldEdad(JTextField jTextFieldEdad) {
        this.jTextFieldEdad = jTextFieldEdad;
    }

    public JButton getjButtonTerminosyCondiciones() {
        return jButtonTerminosyCondiciones;
    }

    public JTextField getjTextFieldNickname() {
        return jTextFieldNickname;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPrivado = new javax.swing.ButtonGroup();
        buttonGroupGenero = new javax.swing.ButtonGroup();
        jPanelDatosIniciales = new javax.swing.JPanel();
        jLabelProvinciaEtiqueta = new javax.swing.JLabel();
        jLabelCedulaEtiqueta = new javax.swing.JLabel();
        jTextFieldCedula = new javax.swing.JTextField();
        jComboBoxProvincia = new javax.swing.JComboBox();
        jButtonBuscarPersona = new javax.swing.JButton();
        jLabelFechaDeNacimientoEtiqueta = new javax.swing.JLabel();
        jComboBoxDiaNacimiento = new javax.swing.JComboBox();
        jComboBoxMesNacimiento = new javax.swing.JComboBox();
        jTextFieldAnnoNacimiento = new javax.swing.JTextField();
        jPanelDatosGeneradosAutomaticamente = new javax.swing.JPanel();
        jLabelNombreEtiqueta = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelPrimerApellidoEtiqueta = new javax.swing.JLabel();
        jTextFieldPrimerApellido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldSegundoApellido = new javax.swing.JTextField();
        jLabelGeneroEtiqueta = new javax.swing.JLabel();
        jRadioButtonGeneroFemenino = new javax.swing.JRadioButton();
        jRadioButtonGeneroMasculino = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelNicknameEtiqueta = new javax.swing.JLabel();
        jTextFieldNickname = new javax.swing.JTextField();
        jLabelContrasenna = new javax.swing.JLabel();
        jPasswordFieldContrasenna = new javax.swing.JPasswordField();
        jButtonRegistrarse = new javax.swing.JButton();
        jLabelDatosPrivadosUsuario = new javax.swing.JLabel();
        jRadioButtonDatosPrivadosUsuario = new javax.swing.JRadioButton();
        jRadioButtonDatosPublicosUsuario = new javax.swing.JRadioButton();
        jLabelAceptarTerminosyCondiciones = new javax.swing.JLabel();
        jButtonTerminosyCondiciones = new javax.swing.JButton();
        jPanelFunesRegistrarNuevoUsuario = new javax.swing.JPanel();
        jLabelFunes = new javax.swing.JLabel();
        jLabelRegistrarNuevoUsuario = new javax.swing.JLabel();
        jButtonSalirDeRegistro = new javax.swing.JButton();
        jPanelDatosIngresados = new javax.swing.JPanel();
        jLabelEdadEtiqueta = new javax.swing.JLabel();
        jTextFieldEdad = new javax.swing.JTextField();
        jLabelLugarDeTrabajoEtiqueta = new javax.swing.JLabel();
        jTextFieldLugarDeTrabajo = new javax.swing.JTextField();
        jLabelCargoQueDesempenaEtiqueta = new javax.swing.JLabel();
        jTextFieldCargoQueDesempena = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelDatosIniciales.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDatosIniciales.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelProvinciaEtiqueta.setText("Provincia: ");

        jLabelCedulaEtiqueta.setText("Cédula: ");

        jTextFieldCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCedulaActionPerformed(evt);
            }
        });

        jComboBoxProvincia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "San José", "Alajuela", "Heredia", "Cartago", "Guanacaste", "Limón" }));

        jButtonBuscarPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/funes/view/imagenes/AbuscarPeque.png"))); // NOI18N
        jButtonBuscarPersona.setBorder(null);
        jButtonBuscarPersona.setContentAreaFilled(false);
        jButtonBuscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarPersonaActionPerformed(evt);
            }
        });

        jLabelFechaDeNacimientoEtiqueta.setText("Fecha de Nacimiento:");

        jComboBoxDiaNacimiento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jComboBoxMesNacimiento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jTextFieldAnnoNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAnnoNacimientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosInicialesLayout = new javax.swing.GroupLayout(jPanelDatosIniciales);
        jPanelDatosIniciales.setLayout(jPanelDatosInicialesLayout);
        jPanelDatosInicialesLayout.setHorizontalGroup(
            jPanelDatosInicialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosInicialesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelDatosInicialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosInicialesLayout.createSequentialGroup()
                        .addGroup(jPanelDatosInicialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCedulaEtiqueta)
                            .addComponent(jLabelProvinciaEtiqueta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelDatosInicialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDatosInicialesLayout.createSequentialGroup()
                        .addComponent(jLabelFechaDeNacimientoEtiqueta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxDiaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxMesNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAnnoNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(jButtonBuscarPersona)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanelDatosInicialesLayout.setVerticalGroup(
            jPanelDatosInicialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosInicialesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanelDatosInicialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProvinciaEtiqueta)
                    .addComponent(jComboBoxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosInicialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCedulaEtiqueta)
                    .addComponent(jTextFieldCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosInicialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBuscarPersona)
                    .addGroup(jPanelDatosInicialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelFechaDeNacimientoEtiqueta)
                        .addComponent(jComboBoxDiaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxMesNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldAnnoNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDatosGeneradosAutomaticamente.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDatosGeneradosAutomaticamente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelNombreEtiqueta.setText("Nombre: ");

        jTextFieldNombre.setEnabled(false);

        jLabelPrimerApellidoEtiqueta.setText("Primer apellido:");

        jTextFieldPrimerApellido.setEnabled(false);

        jLabel1.setText("Segundo apellido:");

        jTextFieldSegundoApellido.setEnabled(false);
        jTextFieldSegundoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSegundoApellidoActionPerformed(evt);
            }
        });

        jLabelGeneroEtiqueta.setText("Género:");

        jRadioButtonGeneroFemenino.setText("F");
        jRadioButtonGeneroFemenino.setEnabled(false);
        jRadioButtonGeneroFemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonGeneroFemeninoActionPerformed(evt);
            }
        });

        jRadioButtonGeneroMasculino.setText("M");
        jRadioButtonGeneroMasculino.setEnabled(false);
        jRadioButtonGeneroMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonGeneroMasculinoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosGeneradosAutomaticamenteLayout = new javax.swing.GroupLayout(jPanelDatosGeneradosAutomaticamente);
        jPanelDatosGeneradosAutomaticamente.setLayout(jPanelDatosGeneradosAutomaticamenteLayout);
        jPanelDatosGeneradosAutomaticamenteLayout.setHorizontalGroup(
            jPanelDatosGeneradosAutomaticamenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosGeneradosAutomaticamenteLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelDatosGeneradosAutomaticamenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPrimerApellidoEtiqueta)
                    .addComponent(jLabelNombreEtiqueta)
                    .addComponent(jLabelGeneroEtiqueta)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosGeneradosAutomaticamenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelDatosGeneradosAutomaticamenteLayout.createSequentialGroup()
                        .addComponent(jRadioButtonGeneroFemenino)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonGeneroMasculino))
                    .addComponent(jTextFieldPrimerApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addComponent(jTextFieldSegundoApellido)
                    .addComponent(jTextFieldNombre))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDatosGeneradosAutomaticamenteLayout.setVerticalGroup(
            jPanelDatosGeneradosAutomaticamenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosGeneradosAutomaticamenteLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosGeneradosAutomaticamenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombreEtiqueta)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosGeneradosAutomaticamenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrimerApellidoEtiqueta)
                    .addComponent(jTextFieldPrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosGeneradosAutomaticamenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldSegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosGeneradosAutomaticamenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGeneroEtiqueta)
                    .addComponent(jRadioButtonGeneroFemenino)
                    .addComponent(jRadioButtonGeneroMasculino))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelNicknameEtiqueta.setText("Nickname: ");

        jTextFieldNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNicknameActionPerformed(evt);
            }
        });

        jLabelContrasenna.setText("Contraseña:");

        jButtonRegistrarse.setText("Registrarse");

        jLabelDatosPrivadosUsuario.setText("Privado:");

        jRadioButtonDatosPrivadosUsuario.setText("Sí");

        jRadioButtonDatosPublicosUsuario.setText("No");

        jLabelAceptarTerminosyCondiciones.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabelAceptarTerminosyCondiciones.setText("Al presionar \"Registrarse\" usted está aceptando nuestros  ");

        jButtonTerminosyCondiciones.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jButtonTerminosyCondiciones.setText("Términos y Condiciones");
        jButtonTerminosyCondiciones.setBorder(null);
        jButtonTerminosyCondiciones.setBorderPainted(false);
        jButtonTerminosyCondiciones.setContentAreaFilled(false);
        jButtonTerminosyCondiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTerminosyCondicionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNicknameEtiqueta)
                            .addComponent(jLabelContrasenna))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordFieldContrasenna, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelDatosPrivadosUsuario)
                                .addGap(59, 59, 59)
                                .addComponent(jRadioButtonDatosPrivadosUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonDatosPublicosUsuario))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelAceptarTerminosyCondiciones)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonTerminosyCondiciones, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(jButtonRegistrarse)
                        .addGap(19, 19, 19))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNicknameEtiqueta)
                    .addComponent(jTextFieldNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContrasenna)
                    .addComponent(jPasswordFieldContrasenna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDatosPrivadosUsuario)
                    .addComponent(jRadioButtonDatosPrivadosUsuario)
                    .addComponent(jRadioButtonDatosPublicosUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonRegistrarse)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelAceptarTerminosyCondiciones)
                        .addComponent(jButtonTerminosyCondiciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanelFunesRegistrarNuevoUsuario.setBackground(new java.awt.Color(153, 0, 153));
        jPanelFunesRegistrarNuevoUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelFunesRegistrarNuevoUsuario.setForeground(new java.awt.Color(255, 255, 255));

        jLabelFunes.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabelFunes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFunes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/funes/view/imagenes/10423616_706622576040724_1115297054_nD.jpg"))); // NOI18N

        jLabelRegistrarNuevoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jLabelRegistrarNuevoUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelRegistrarNuevoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRegistrarNuevoUsuario.setText("Registrarse");

        jButtonSalirDeRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/funes/view/imagenes/Button-Close-icon_1.png"))); // NOI18N
        jButtonSalirDeRegistro.setBorder(null);
        jButtonSalirDeRegistro.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanelFunesRegistrarNuevoUsuarioLayout = new javax.swing.GroupLayout(jPanelFunesRegistrarNuevoUsuario);
        jPanelFunesRegistrarNuevoUsuario.setLayout(jPanelFunesRegistrarNuevoUsuarioLayout);
        jPanelFunesRegistrarNuevoUsuarioLayout.setHorizontalGroup(
            jPanelFunesRegistrarNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFunesRegistrarNuevoUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFunes, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelFunesRegistrarNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFunesRegistrarNuevoUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabelRegistrarNuevoUsuario)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFunesRegistrarNuevoUsuarioLayout.createSequentialGroup()
                        .addComponent(jButtonSalirDeRegistro)
                        .addContainerGap())))
        );
        jPanelFunesRegistrarNuevoUsuarioLayout.setVerticalGroup(
            jPanelFunesRegistrarNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFunesRegistrarNuevoUsuarioLayout.createSequentialGroup()
                .addGroup(jPanelFunesRegistrarNuevoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFunesRegistrarNuevoUsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelFunes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelFunesRegistrarNuevoUsuarioLayout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addComponent(jButtonSalirDeRegistro)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelRegistrarNuevoUsuario)))
                .addContainerGap())
        );

        jPanelDatosIngresados.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDatosIngresados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelEdadEtiqueta.setText("Edad: ");

        jTextFieldEdad.setEditable(false);
        jTextFieldEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEdadActionPerformed(evt);
            }
        });

        jLabelLugarDeTrabajoEtiqueta.setText("Lugar de trabajo:");

        jTextFieldLugarDeTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLugarDeTrabajoActionPerformed(evt);
            }
        });

        jLabelCargoQueDesempenaEtiqueta.setText("Cargo: ");

        javax.swing.GroupLayout jPanelDatosIngresadosLayout = new javax.swing.GroupLayout(jPanelDatosIngresados);
        jPanelDatosIngresados.setLayout(jPanelDatosIngresadosLayout);
        jPanelDatosIngresadosLayout.setHorizontalGroup(
            jPanelDatosIngresadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosIngresadosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelDatosIngresadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLugarDeTrabajoEtiqueta)
                    .addComponent(jLabelCargoQueDesempenaEtiqueta)
                    .addComponent(jLabelEdadEtiqueta))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosIngresadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDatosIngresadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldLugarDeTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                        .addComponent(jTextFieldCargoQueDesempena)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDatosIngresadosLayout.setVerticalGroup(
            jPanelDatosIngresadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosIngresadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosIngresadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEdadEtiqueta)
                    .addComponent(jTextFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosIngresadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLugarDeTrabajoEtiqueta)
                    .addComponent(jTextFieldLugarDeTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosIngresadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCargoQueDesempenaEtiqueta)
                    .addComponent(jTextFieldCargoQueDesempena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFunesRegistrarNuevoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelDatosIniciales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelDatosGeneradosAutomaticamente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelDatosIngresados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelFunesRegistrarNuevoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDatosIniciales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDatosGeneradosAutomaticamente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDatosIngresados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCedulaActionPerformed

    private void jTextFieldSegundoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSegundoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSegundoApellidoActionPerformed

    private void jButtonBuscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarPersonaActionPerformed

    private void jTextFieldAnnoNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAnnoNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAnnoNacimientoActionPerformed

    private void jTextFieldEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEdadActionPerformed

    private void jTextFieldLugarDeTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLugarDeTrabajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLugarDeTrabajoActionPerformed

    private void jTextFieldNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNicknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNicknameActionPerformed

    private void jRadioButtonGeneroFemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonGeneroFemeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonGeneroFemeninoActionPerformed

    private void jRadioButtonGeneroMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonGeneroMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonGeneroMasculinoActionPerformed

    private void jButtonTerminosyCondicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTerminosyCondicionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTerminosyCondicionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroNuevoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroNuevoUsuario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupGenero;
    private javax.swing.ButtonGroup buttonGroupPrivado;
    private javax.swing.JButton jButtonBuscarPersona;
    private javax.swing.JButton jButtonRegistrarse;
    private javax.swing.JButton jButtonSalirDeRegistro;
    private javax.swing.JButton jButtonTerminosyCondiciones;
    private javax.swing.JComboBox jComboBoxDiaNacimiento;
    private javax.swing.JComboBox jComboBoxMesNacimiento;
    private javax.swing.JComboBox jComboBoxProvincia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAceptarTerminosyCondiciones;
    private javax.swing.JLabel jLabelCargoQueDesempenaEtiqueta;
    private javax.swing.JLabel jLabelCedulaEtiqueta;
    private javax.swing.JLabel jLabelContrasenna;
    private javax.swing.JLabel jLabelDatosPrivadosUsuario;
    private javax.swing.JLabel jLabelEdadEtiqueta;
    private javax.swing.JLabel jLabelFechaDeNacimientoEtiqueta;
    private javax.swing.JLabel jLabelFunes;
    private javax.swing.JLabel jLabelGeneroEtiqueta;
    private javax.swing.JLabel jLabelLugarDeTrabajoEtiqueta;
    private javax.swing.JLabel jLabelNicknameEtiqueta;
    private javax.swing.JLabel jLabelNombreEtiqueta;
    private javax.swing.JLabel jLabelPrimerApellidoEtiqueta;
    private javax.swing.JLabel jLabelProvinciaEtiqueta;
    private javax.swing.JLabel jLabelRegistrarNuevoUsuario;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelDatosGeneradosAutomaticamente;
    private javax.swing.JPanel jPanelDatosIngresados;
    private javax.swing.JPanel jPanelDatosIniciales;
    private javax.swing.JPanel jPanelFunesRegistrarNuevoUsuario;
    private javax.swing.JPasswordField jPasswordFieldContrasenna;
    private javax.swing.JRadioButton jRadioButtonDatosPrivadosUsuario;
    private javax.swing.JRadioButton jRadioButtonDatosPublicosUsuario;
    private javax.swing.JRadioButton jRadioButtonGeneroFemenino;
    private javax.swing.JRadioButton jRadioButtonGeneroMasculino;
    private javax.swing.JTextField jTextFieldAnnoNacimiento;
    private javax.swing.JTextField jTextFieldCargoQueDesempena;
    private javax.swing.JTextField jTextFieldCedula;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldLugarDeTrabajo;
    private javax.swing.JTextField jTextFieldNickname;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPrimerApellido;
    private javax.swing.JTextField jTextFieldSegundoApellido;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarMensajeError(String mensaje, String titulo) {
        JOptionPane.showMessageDialog(null,
                mensaje,
                titulo,
                JOptionPane.ERROR_MESSAGE);
    }

    @Override
    public void mostrarVentana() {
        setVisible(true);
    }

    @Override
    public void ocultarVentana() {
        setVisible(false);
    }

    @Override
    public void setSexo(String sexo) {
        if (sexo.equals("1")) {
            jRadioButtonGeneroMasculino.setSelected(true);
            jRadioButtonGeneroFemenino.setSelected(false);
        } else if ((sexo.equals("2"))) {
            jRadioButtonGeneroMasculino.setSelected(false);
            jRadioButtonGeneroFemenino.setSelected(true);
        }

    }

    @Override
    public void setNombre(String nombre) {
        jTextFieldNombre.setText(nombre);
    }

    @Override
    public String getNombre() {
        return jTextFieldNombre.getText();
    }

    @Override
    public void setPrimerApellido(String apellido) {
        jTextFieldPrimerApellido.setText(apellido);
    }

    @Override
    public String getPrimerApellido() {
        return jTextFieldPrimerApellido.getText();
    }

    @Override
    public String getPrivado() {
        if (jRadioButtonDatosPrivadosUsuario.isSelected()) {
            return "Privado";
        } else if (jRadioButtonDatosPublicosUsuario.isSelected()) {
            return "Publico";
        }
        return "";
    }

    @Override
    public void setSegundoApellido(String apellido) {
        jTextFieldSegundoApellido.setText(apellido);
    }

    @Override
    public String getSegundoApellido() {
        return jTextFieldSegundoApellido.getText();
    }

    @Override
    public void setEdad(String edad) {
        jTextFieldEdad.setText(edad);
    }

    @Override
    public void setBusquedaExitosa(boolean exitoso) {
        busquedaExitosa = exitoso;
    }

    @Override
    public void setCedula(String cedula) {
        cedulaActual = cedula;
        jTextFieldCedula.setText(cedula);
    }

    @Override
    public String getCedula() {
        return jTextFieldCedula.getText();

    }

    @Override
    public String getProvincia() {
        return jComboBoxProvincia.getSelectedItem().toString();
    }

    @Override
    public String getDiaNacimiento() {
        return jComboBoxDiaNacimiento.getSelectedItem().toString();
    }

    @Override
    public String getMesNacimiento() {
        return jComboBoxMesNacimiento.getSelectedItem().toString();
    }

    @Override
    public String getAnnoNacimiento() {
        return jTextFieldAnnoNacimiento.getText();
    }

    @Override
    public String getEdad() {
        return jTextFieldEdad.getText();
    }

    @Override
    public String getLugarDeTrabajo() {
        return jTextFieldLugarDeTrabajo.getText();
    }

    @Override
    public String getCargo() {
        return jTextFieldCargoQueDesempena.getText();
    }

    @Override
    public String getNickname() {
        return jTextFieldNickname.getText();
    }

    @Override
    public String getContrasenna() {
        String contrasenna = new String(jPasswordFieldContrasenna.getPassword());
        return contrasenna;
    }

    @Override
    public String getGenero() {
        if (jRadioButtonGeneroFemenino.isSelected()) {
            return "2";
        } else {
            return "1";
        }
    }

    @Override
    public void setAnnoNacimiento() {
        jTextFieldAnnoNacimiento.setText("");
    }

    @Override
    public void setLugarDeTrabajo() {
        jTextFieldLugarDeTrabajo.setText("");
    }

    @Override
    public void setCargo() {
        jTextFieldCargoQueDesempena.setText("");
    }

    @Override
    public void setNickname() {
        jTextFieldNickname.setText("");
    }

    @Override
    public void setContrasenna() {
        jPasswordFieldContrasenna.setText("");
    }

}
